FROM docker.io/library/golang:1.22-alpine

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y gcc

RUN go mod tidy

RUN go build -o matches cmd/matches/main.go

EXPOSE 8080

CMD ["./matches"]