version: "3.9"
services:
  matches:
    build:
      context: ..
      dockerfile: podman/Dockerfile.matches
    ports:
      - "8080:8080"
    restart: always
    container_name: matches_service
    networks:
      - volley_network
    depends_on:
      - database

  sets:
    build:
      context: ..
      dockerfile: podman/Dockerfile.sets
    ports:
      - "8081:8081"
    restart: always
    container_name: sets_service
    networks:
      - volley_network
    depends_on:
      - database

networks:
  volley_network:
    driver: bridge

volumes:
  postgres_data:
